# Generated by Django 6.0.6 on 2026-06-22 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la cuenta')),
                ('banco', models.CharField(max_length=100)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pendiente', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('CANCELADO', 'Cancelado'), ('PAGADO_PARCIAL', 'Pagado Parcial'), ('PAGADO_TOTAL', 'Pagado Total')], default='PENDIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Efectuar'), ('EFECTUADO', 'Efectuado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('token_duplicado', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesoreria.cuentabancaria')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tesoreria.gasto')),
            ],
        ),
    ]
